baseurl = "https://beaucarrillo.com"
languageCode = "en-us"
title = "Adam Carrillo Architecture"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "The author"
    site_description = "The Blog"
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/hugo.png"
    header_background = "img/desk.jpg"
    header_title = "Hugo Test Site"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""
